"""base models id type modified

Revision ID: fb8a8102b994
Revises: ffddec5395bd
Create Date: 2022-04-12 13:44:33.490175

"""
from alembic import op
import sqlalchemy as sa
import common.guid_type


# revision identifiers, used by Alembic.
revision = 'fb8a8102b994'
down_revision = 'ffddec5395bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
