"""base models modified

Revision ID: ffddec5395bd
Revises: dad4867c7857
Create Date: 2022-04-12 13:41:53.669766

"""
from alembic import op
import sqlalchemy as sa
import common.guid_type


# revision identifiers, used by Alembic.
revision = 'ffddec5395bd'
down_revision = 'dad4867c7857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('rules', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('worklogs', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('worklogs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worklogs', 'updated_at')
    op.drop_column('worklogs', 'created_at')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_column('rules', 'updated_at')
    op.drop_column('rules', 'created_at')
    # ### end Alembic commands ###
